[package]
name = "webdav-server"

# When releasing to crates.io:
# - Update html_root_url in src/main.rs
# - Update CHANGELOG.md.
# - Create git tag webdav-server-0.x.y
version = "0.5.4"

description = "webdav/http server with support for user accounts"
readme = "README.md"
documentation = "https://docs.rs/webdav-server"
repository = "https://github.com/difeid/webdav-server-rs"
homepage = "https://github.com/difeid/webdav-server-rs"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>", "Danil <git@danil.contact>"]
edition = "2018"
license = "Apache-2.0"
categories = ["filesystem"]

[workspace]

[features]
# By default, the "pam" and "quota" features are enabled.
#
# Some systems do not have pam (like OpenBSD), so to compile this
# package without pam but with quota use:
#
#     cargo build --release --no-default-features --features=quota
#
default = [ "pam", "quota" ]

# dependencies for the feature.
pam = [ "pam-sandboxed" ]
quota = [ "fs-quota" ]

# Include debug info in release builds.
[profile.release]
debug = false

# Build dependencies in optimized mode, even for debug builds.
[profile.dev.package."*"]
opt-level = 3

# Build dev-dependencies in non-optimized mode, even for release builds.
[profile.dev.build-override]
opt-level = 0

[dependencies]
clap = "2.34.0"
env_logger = "0.11.11"
fs-quota = { path = "fs_quota", version = "0.1.0", optional = true }
futures = "0.3.34"
headers = "0.3.9"
http = "0.2.12"
hyper = { version = "0.14.32", features = [ "http1", "http2", "server", "stream", "runtime" ] }
lazy_static = "1.5.0"
libc = "0.2.189"
log = "0.4.34"
nix = { version = "0.29.0", features = ["fs"] }
pam-sandboxed = { path = "pam", version = "0.2.0", optional = true }
regex = "1.12.4"
rustls-pemfile = "1.0.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
socket2 = { version = "0.6.5", features = ["all"] }
tls-listener = { version = "0.7.0", features = [ "hyper-h1", "hyper-h2", "rustls" ] }
tokio = { version = "1.52.4", features = ["full"] }
tokio-rustls = "0.24.1"
toml = "1.1.4"
url = "2.5.8"
webdav-handler = "0.2.0"
pwhash = "1.0.0"
